name: For each commit and PR
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
    - name: Run golangci-lint
      run: make lint
